[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma generate --generator client && npx prisma migrate deploy && node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3