-- AlterTable
ALTER TABLE "MedicionHistorica" ADD COLUMN     "caudalEntrada" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "caudalSalida" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "temperatura" DOUBLE PRECISION NOT NULL DEFAULT 0;
